import React from "react";

export default function PromoterDetailAdminModal({ promoter, leads = [], onClose }) {
  if (!promoter) return null;

  // Filter leads generated by this specific promoter
  const promoterLeads = leads.filter(
    (l) => l.promoterId === promoter.promoterId
  );

  return (
    <div className="fixed inset-0 z-[100] bg-[#070F21]/80 backdrop-blur-sm flex items-start justify-center p-4 pt-24 overflow-hidden">
      <div className="bg-[#0F1C3F] border border-blue-900/40 rounded-3xl w-full max-w-4xl max-h-[calc(100vh-120px)] overflow-y-auto shadow-2xl animate-scale-up">
        {/* Header */}
        <div className="p-6 border-b border-blue-900/30 flex items-center justify-between">
          <div>
            <h3 className="text-lg font-black text-white">{promoter.name} (Agency Inspection)</h3>
            <p className="text-xs text-blue-300 mt-1">Promoter ID: <span className="font-mono text-amber-400 font-bold uppercase">{promoter.promoterId}</span> | Registered: {promoter.createdAt}</p>
          </div>
          <button 
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-[#070F21] hover:bg-blue-950 flex items-center justify-center text-blue-300 hover:text-blue-100 transition-all font-bold cursor-pointer"
          >
            ✕
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-6 text-xs font-semibold text-slate-300">
          {/* Promoter Quick Profile */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 bg-[#070F21]/50 p-4 border border-blue-900/30 rounded-2xl">
            <div>
              <span className="text-[10px] text-blue-300 font-bold uppercase tracking-wider block">Email Address</span>
              <span className="text-sm font-bold text-white block mt-0.5">{promoter.email}</span>
            </div>
            <div>
              <span className="text-[10px] text-blue-300 font-bold uppercase tracking-wider block">Phone Number</span>
              <span className="text-sm font-bold text-white block mt-0.5">{promoter.phone || "N/A"}</span>
            </div>
            <div>
              <span className="text-[10px] text-blue-300 font-bold uppercase tracking-wider block">Commission Balance</span>
              <span className="text-sm font-black text-emerald-400 block mt-0.5">Rs. {promoter.totalCommission?.toLocaleString()}</span>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Dynamic Referred Client Status */}
            <div className="bg-[#070F21]/20 border border-blue-900/30 p-5 rounded-2xl space-y-4">
              <h4 className="text-[11px] font-black uppercase text-blue-300 tracking-wider border-b border-blue-900/30 pb-2">
                Referred Clients Status ({promoter.referredClients?.length || 0})
              </h4>
              <div className="space-y-3 max-h-[300px] overflow-y-auto pr-1 scrollbar-none">
                {!promoter.referredClients || promoter.referredClients.length === 0 ? (
                  <p className="text-blue-400 italic py-6 text-center">No clients referred yet.</p>
                ) : (
                  promoter.referredClients.map((client) => (
                    <div 
                      key={client.id}
                      className="p-3 border border-blue-900/20 bg-[#070F21]/40 rounded-xl flex items-center justify-between gap-3"
                    >
                      <div>
                        <p className="font-bold text-white text-xs">{client.name}</p>
                        <p className="text-[10px] text-blue-400 mt-0.5">{client.email}</p>
                        {client.policyName && (
                          <p className="text-[10px] text-emerald-400 mt-1 font-bold">
                            Policy: {client.policyName} (Rs. {client.premium.toLocaleString()})
                          </p>
                        )}
                      </div>
                      <span className={`px-2 py-0.5 text-[8px] font-black rounded-full uppercase tracking-wider ${
                        client.hasPolicy 
                          ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20" 
                          : "bg-blue-500/10 text-blue-400 border border-blue-500/20"
                      }`}>
                        {client.status}
                      </span>
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* Dynamic Sales Lead Tracker */}
            <div className="bg-[#070F21]/20 border border-blue-900/30 p-5 rounded-2xl space-y-4">
              <h4 className="text-[11px] font-black uppercase text-blue-300 tracking-wider border-b border-blue-900/30 pb-2">
                Sales Pipeline Leads ({promoterLeads.length})
              </h4>
              <div className="space-y-3 max-h-[300px] overflow-y-auto pr-1 scrollbar-none">
                {promoterLeads.length === 0 ? (
                  <p className="text-blue-400 italic py-6 text-center">No logged leads on record.</p>
                ) : (
                  promoterLeads.map((lead) => (
                    <div 
                      key={lead._id}
                      className="p-3 border border-blue-900/20 bg-[#070F21]/40 rounded-xl space-y-2"
                    >
                      <div className="flex items-center justify-between gap-3">
                        <div>
                          <p className="font-bold text-white text-xs">{lead.fullName}</p>
                          <p className="text-[10px] text-blue-400">{lead.phone} • {lead.email || "No Email"}</p>
                        </div>
                        <span className={`px-2 py-0.5 text-[8px] font-black rounded-full uppercase tracking-wider ${
                          lead.status === "Converted" 
                            ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20" 
                            : lead.status === "Proposal Submitted" 
                            ? "bg-purple-500/10 text-purple-400 border border-purple-500/20" 
                            : lead.status === "Contacted" 
                            ? "bg-blue-500/10 text-blue-400 border border-blue-500/20" 
                            : "bg-blue-900/20 text-blue-300 border border-blue-800/30"
                        }`}>
                          {lead.status}
                        </span>
                      </div>
                      {lead.notes && (
                        <p className="text-[10px] text-amber-500 bg-amber-500/5 px-2 py-1 rounded border border-amber-500/10 font-medium">
                          Notes: {lead.notes}
                        </p>
                      )}
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-blue-900/30 flex items-center justify-end bg-[#070F21]/20">
          <button 
            onClick={onClose}
            className="px-5 py-2 bg-blue-950 hover:bg-blue-900 border border-blue-800/40 text-xs font-bold text-white rounded-xl transition-all cursor-pointer"
          >
            Close Activity Log
          </button>
        </div>
      </div>
    </div>
  );
}
